version: 2

sources:
  - name: staging
    database: first-provider-397409
    schema: dezoomcamp
    tables:
      - name: yellow_rides
      - name: green_rides
      - name: fvh_data

models:
  - name: stg_green_tripdata
    description: >
      trips made by the green taxis
    columns:
      - name: tripid
        description: primary key of this table
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn
      - name: vendorid
        description: >
          code indicating provider of the record
      - name: pickup_locationid
        description: location where the meter was engaged
        tests:
          - relationships:
              field: locationid
              to: ref('taxi_zone_lookup')
              severity: warn
      - name: dropoff_locationid
        description: location where the meter was engaged
        tests:
          - relationships:
              field: locationid
              to: ref('taxi_zone_lookup')
              severity: warn
      - name: payment_type
        description: type of the payment
        tests:
          - accepted_values:
              values:
                - "{{ var('payment_type_values')}}"
              severity: warn
              quote: false
